print ("hello git 2. py")
print("vamos a crear tags en git y a crear ramas en git")
print("agregamos mas codigo en la rama main sin afectar la rama login")
print("ahora agregaremos un merge pero con conflictos para aprender a resolverlos")
print("ahora vamos a resolver los conflictos en git")